### PR TITLE
Add our first unit test

### LINKED ISSUE #30: Let's write a unit test or two
Since we are testing something that is highly coupled to an external service, here are some suggested ground rules to clarify a useful test:

* We do not want 100% coverage from unit tests.
* The goal is to lessen the amount of manual testing as we develop.
* If you've managed to write a function that is isolated, test away! The CLI probably won't have many of these.
* Smoke tests. Verify that every idempotent command/flag generates expected output when the API returns "happy path" json.
* Exercise error handling for common anticipated scenarios, like handling a 404 from a fat fingered `get <name>` command. Mostly to encourage us to do something useful with expected errors, instead of just bubbling it up directly to the console.
* Anything more involved than a GET, or relies on back-n-forth with the API, should be an integration test. Don't mock API behavior.

### PR DESCRIPTION
**Pull request by carolynvs**
* Added notes on how to run and update testdata using `make test` and `make test UPDATE_GOLDEN=true` to our contributing.
* Added failing test to demonstrate how it all looks when a test fails. Will fix before merging. 😉
* Tweaked command constructor to pass in an alternate output so we can validate test output.
* I pulled in pkg/errors because stack traces make troubleshooting failing tests so much easier.

TODO
- [x] Need to setup a test http server in the test and point our kubeconfig at it.
- [x] ~Once we are okay with this, I'll remove the temporary function and plumb the rest of the commands with the alternate output.~ oops, I had to do it sooner than I had thought because reasons. 😀 

Closes #30

### CODE REVIEW

**Comment by arschles** [comment]
@carolynvs looks like CI failure is legit

**Comment by carolynvs** [comment]
@arschles Yup! I broke it on purpose (see the OP) so that people could see what a failing test would look like. I'll fix it before merging if everything else is good.

**Comment by carolynvs** [comment]
I've fixed the purposefully failing test and got a passing build. Is it okay for me to merge or do we want another set of 👀?

**Comment by arschles** [comment]
@carolynvs this needs a rebase 😦

**Pull request merged**
